<?xml version='1.0' encoding='utf-8'?>
<package format="3">
  <name>webots_ros2_bridge</name>
  <version>1.0.1</version>
  <description>Local relay bridge between Webots and two ROS 2 Brain teams.</description>
  <maintainer email="sim@example.com">Webots 5v5 Brain Simulator contributors</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>builtin_interfaces</exec_depend>
  <exec_depend>rosgraph_msgs</exec_depend>
  <exec_depend>booster_msgs</exec_depend>
  <exec_depend>booster_interface</exec_depend>
  <exec_depend>game_controller_interface</exec_depend>
  <exec_depend>game_controller</exec_depend>
  <exec_depend>brain_red_v3</exec_depend>
  <exec_depend>brain_blue_wangyifei_v1</exec_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
