"""Webots-side gateway for the Webots 5v5 Brain Simulator.

This controller owns only simulation mechanics and match state:
- applies velocity commands generated by the external Brain;
- applies kick requests;
- publishes world truth over UDP;
- simulates fall/get-up state and basic match restarts;
- monitors the ball and restores it after clearly invalid physics states;
- exposes compact command/link diagnostics.

There is deliberately no role assignment, behavior tree, chase logic, pass
selection, or shooting decision in this file. The uploaded C++ Brain remains
the only decision layer.
"""
from __future__ import annotations

import json
import math
import os
import socket
import sys
from dataclasses import dataclass
from pathlib import Path

from controller import Supervisor

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))
from geometry import clamp, local_to_world, world_to_local, wrap_angle, yaw_tilt_rotation

ROBOT_NAMES = [f"{team}_{i}" for team in ("red", "blue") for i in range(1, 6)]
DEF_NAMES = {name: name.upper() for name in ROBOT_NAMES}
SPAWNS = {
    "red_1": (-9.0, 0.0, 0.0),
    "red_2": (-6.2, 2.6, 0.0),
    "red_3": (-6.2, -2.6, 0.0),
    "red_4": (-3.6, 0.0, 0.0),
    "red_5": (-1.7, 1.4, 0.0),
    "blue_1": (9.0, 0.0, math.pi),
    "blue_2": (6.2, -2.6, math.pi),
    "blue_3": (6.2, 2.6, math.pi),
    "blue_4": (3.6, 0.0, math.pi),
    "blue_5": (1.7, -1.4, math.pi),
}


@dataclass
class MotionCommand:
    vx: float = 0.0
    vy: float = 0.0
    vyaw: float = 0.0
    received_at: float = -1e9
    packet_count: int = 0


@dataclass
class RobotRuntime:
    x: float
    y: float
    yaw: float
    vx: float = 0.0
    vy: float = 0.0
    vyaw: float = 0.0
    walk_phase: float = 0.0
    recovery_state: int = 0  # 0 ready, 1 falling, 2 fallen, 3 getting up
    recovery_started: float = 0.0
    recovery_available: bool = True
    last_kick: float = -1e9
    collision_lock_until: float = -1e9
    last_collision_fall: float = -1e9
    avoidance_until: float = -1e9
    avoidance_cooldown_until: float = -1e9
    avoidance_world_vx: float = 0.0
    avoidance_world_vy: float = 0.0
    avoidance_pending: bool = False


class Gateway:
    def __init__(self):
        self.robot = Supervisor()
        self.step_ms = int(self.robot.getBasicTimeStep())
        self.dt = self.step_ms / 1000.0

        cfg_path = ROOT / "config" / "bridge.json"
        self.cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
        self.initial_kicking_team = str(
            self.cfg.get("initial_kicking_team", "red")
        ).lower()
        if self.initial_kicking_team not in self.cfg["team_ids"]:
            raise ValueError(
                f"initial_kicking_team must be one of {sorted(self.cfg['team_ids'])}"
            )
        self.ros_host = os.environ.get("WEBOTS_ROS_HOST", self.cfg["ros_bridge_host"])
        self.state_port = int(os.environ.get("WEBOTS_STATE_PORT", self.cfg["state_port"]))
        self.command_port = int(os.environ.get("WEBOTS_COMMAND_PORT", self.cfg["command_port"]))
        self.state_target = (self.ros_host, self.state_port)

        self.tx = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.rx = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.rx.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self.rx.bind(("0.0.0.0", self.command_port))
        self.rx.setblocking(False)

        self.keyboard = self.robot.getKeyboard()
        self.keyboard.enable(self.step_ms)

        self.ball = self.robot.getFromDef("BALL")
        if self.ball is None:
            raise RuntimeError("Missing DEF BALL")
        self.ball_field = self.ball.getField("translation")

        self.nodes = {name: self.robot.getFromDef(DEF_NAMES[name]) for name in ROBOT_NAMES}
        missing = [name for name, node in self.nodes.items() if node is None]
        if missing:
            raise RuntimeError(f"Missing DEF robots: {missing}")
        self.trans = {name: node.getField("translation") for name, node in self.nodes.items()}
        self.rot = {name: node.getField("rotation") for name, node in self.nodes.items()}

        self.runtime = {name: RobotRuntime(*SPAWNS[name]) for name in ROBOT_NAMES}
        self.commands = {name: MotionCommand() for name in ROBOT_NAMES}

        self.score = {"red": 0, "blue": 0}
        self.phase = "READY"
        self.phase_started = self.robot.getTime()
        self.match_time = 0.0
        self.last_time = self.robot.getTime()
        self.last_state_tx = -1e9
        self.last_event = f"match created; {self.initial_kicking_team.upper()} kickoff"
        self.last_touch = None

        self.state_packets_sent = 0
        self.command_packets_received = 0
        self.move_packets_received = 0
        self.kick_packets_received = 0
        self.kick_packets_applied = 0
        self.kick_packets_rejected_distance = 0
        self.invalid_command_packets = 0
        self.bridge_status_packets_received = 0
        self.bridge_state_packets_received = 0
        self.last_bridge_ack_time = -1e9
        self.last_command_robot = "none"
        self.last_command_time = -1e9
        self.last_diag_time = -1e9
        self.last_ball_log_time = -1e9
        self.no_command_warning_printed = False
        self.no_state_ack_warning_printed = False
        self.debug_move_until = -1e9

        self.ball_guard_cfg = {
            "enabled": True,
            "nominal_z": 0.12,
            "min_z": -0.05,
            "max_z": 3.0,
            "safety_x": 13.5,
            "safety_y": 9.0,
            "max_linear_speed": 12.0,
            "log_period": 2.0,
            **self.cfg.get("ball_guard", {}),
        }
        self.collision_guard_cfg = self.cfg.get("collision_guard", {})
        self.ball_physics_cfg = self.cfg.get("ball_physics", {})
        self.referee_cfg = self.cfg.get("referee", {"mode": "internal_simulated"})
        self.ball_resets = 0
        self.ball_velocity_clamps = 0
        self.robot_overlap_resolutions = 0
        self.robot_collision_impacts = 0
        self.robot_collision_falls = 0
        self.robot_collision_avoids = 0
        self.ball_drag_steps = 0
        self.last_overlap_log_time = -1e9
        self.last_safe_ball_position = [0.0, 0.0, float(self.ball_guard_cfg["nominal_z"])]

        self.set_play = 0
        self.stopped = 0
        self.kicking_team = self.cfg["team_ids"][self.initial_kicking_team]
        self.restart_release_at = 0.0
        # Monotonic event id consumed by the simulated game_controller node.
        # The gateway reports restart facts; game_controller owns when set_play ends.
        self.restart_id = 0
        self.restart_started_at = 0.0
        self.restart_ball_position = [0.0, 0.0]

        self.reset_positions(reset_score=True)
        print(f"[WEBOTS_GATEWAY] UDP commands :{self.command_port}; state -> {self.state_target}")
        print("[WEBOTS_GATEWAY] Webots 5v5 Brain Simulator 1.0.2")
        print(f"[WEBOTS_GATEWAY] initial kickoff team: {self.initial_kicking_team.upper()}")

    @staticmethod
    def finite_float(value, default=0.0):
        try:
            parsed = float(value)
        except (TypeError, ValueError):
            return default, False
        return (parsed, True) if math.isfinite(parsed) else (default, False)

    def place_ball(self, position, reason=None):
        safe_position = [float(position[0]), float(position[1]), float(position[2])]
        self.ball_field.setSFVec3f(safe_position)
        self.ball.resetPhysics()
        self.ball.setVelocity([0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
        self.last_safe_ball_position = list(safe_position)
        if reason:
            print(
                f"[WEBOTS_GATEWAY][BALL] placed at "
                f"({safe_position[0]:+.3f},{safe_position[1]:+.3f},{safe_position[2]:+.3f}) "
                f"reason={reason}"
            )

    def reset_ball_guard(self, reason):
        self.ball_resets += 1
        self.last_event = f"ball auto-reset: {reason}"
        self.place_ball(
            [0.0, 0.0, float(self.ball_guard_cfg["nominal_z"])],
            reason=f"AUTO-RESET #{self.ball_resets}: {reason}",
        )

    def reset_positions(self, reset_score=False):
        if reset_score:
            self.score = {"red": 0, "blue": 0}
            self.match_time = 0.0
        for name, (x, y, yaw) in SPAWNS.items():
            runtime = self.runtime[name]
            runtime.x = x
            runtime.y = y
            runtime.yaw = yaw
            runtime.vx = runtime.vy = runtime.vyaw = 0.0
            runtime.recovery_state = 0
            runtime.collision_lock_until = -1e9
            runtime.last_collision_fall = -1e9
            runtime.avoidance_until = -1e9
            runtime.avoidance_cooldown_until = -1e9
            runtime.avoidance_world_vx = 0.0
            runtime.avoidance_world_vy = 0.0
            runtime.avoidance_pending = False
            self.trans[name].setSFVec3f([x, y, 0.0])
            self.rot[name].setSFRotation([0, 0, 1, yaw])
            self.nodes[name].resetPhysics()
            self.commands[name] = MotionCommand()
        self.place_ball([0.0, 0.0, float(self.ball_guard_cfg["nominal_z"])])
        self.phase = "READY"
        self.phase_started = self.robot.getTime()
        self.set_play = 0
        self.stopped = 0
        self.kicking_team = self.cfg["team_ids"][self.initial_kicking_team]
        self.last_touch = None

    def receive_commands(self):
        while True:
            try:
                raw, _ = self.rx.recvfrom(65535)
            except BlockingIOError:
                break
            try:
                msg = json.loads(raw.decode("utf-8"))
            except Exception:
                self.invalid_command_packets += 1
                continue
            if msg.get("version") != 1:
                continue

            now = self.robot.getTime()
            message_type = msg.get("type")
            if message_type == "bridge_status":
                self.bridge_status_packets_received += 1
                self.last_bridge_ack_time = now
                try:
                    self.bridge_state_packets_received = int(msg.get("state_rx", 0))
                except (TypeError, ValueError):
                    self.bridge_state_packets_received = 0
                if self.bridge_status_packets_received == 1:
                    print("[WEBOTS_GATEWAY] first Bridge world-state ACK received")
                continue

            if message_type != "robot_command":
                continue

            self.command_packets_received += 1
            name = str(msg.get("robot", "")).lower()
            if name not in self.runtime:
                self.invalid_command_packets += 1
                continue
            self.last_command_robot = name
            self.last_command_time = now
            action = msg.get("action")

            if action == "move":
                self.move_packets_received += 1
                if self.move_packets_received == 1:
                    print(f"[WEBOTS_GATEWAY] first Brain move command received from {name}")
                vx, ok_x = self.finite_float(msg.get("vx", 0.0))
                vy, ok_y = self.finite_float(msg.get("vy", 0.0))
                vyaw, ok_yaw = self.finite_float(msg.get("vyaw", 0.0))
                if not (ok_x and ok_y and ok_yaw):
                    self.invalid_command_packets += 1
                    print(f"[WEBOTS_GATEWAY][WARN] rejected non-finite move command from {name}")
                    continue
                motion_cfg = self.cfg["motion"]
                command = self.commands[name]
                command.vx = clamp(vx, -motion_cfg["max_vx"], motion_cfg["max_vx"])
                command.vy = clamp(vy, -motion_cfg["max_vy"], motion_cfg["max_vy"])
                command.vyaw = clamp(vyaw, -motion_cfg["max_vyaw"], motion_cfg["max_vyaw"])
                command.received_at = now
                command.packet_count += 1
            elif action == "get_up":
                self.start_get_up(name)
            elif action == "kick":
                self.kick_packets_received += 1
                self.apply_kick(name, msg)
            elif action == "fall":
                self.start_fall(name)
            elif action == "reset":
                self.reset_positions(reset_score=bool(msg.get("reset_score", False)))

    def robot_motion_limits(self):
        field = self.cfg["field"]
        margin = float(field.get("robot_edge_margin", 0.35))
        return (
            float(field.get("turf_length", field["length"])) / 2.0 - margin,
            float(field.get("turf_width", field["width"])) / 2.0 - margin,
        )

    @staticmethod
    def approach(current, target, delta):
        return min(current + delta, target) if current < target else max(current - delta, target)

    def start_fall(self, name):
        runtime = self.runtime[name]
        if runtime.recovery_state == 0:
            # Preserve an already selected collision escape so it runs after
            # the fall/get-up animation instead of expiring while grounded.
            if runtime.avoidance_until > self.robot.getTime():
                runtime.avoidance_pending = True
            runtime.recovery_state = 1
            runtime.recovery_started = self.robot.getTime()
            runtime.vx = runtime.vy = runtime.vyaw = 0.0
            self.last_event = f"{name} fell"

    def start_get_up(self, name):
        runtime = self.runtime[name]
        if runtime.recovery_state in (1, 2):
            runtime.recovery_state = 3
            runtime.recovery_started = self.robot.getTime()
            self.last_event = f"{name} get-up requested"

    def schedule_collision_avoidance(self, name, world_vx, world_vy, now):
        """Temporarily override the Brain command to leave a contact deadlock.

        A fallen robot stores the escape vector and executes it immediately after
        getting up. Ready robots execute it now. The cooldown prevents a contact
        cluster from choosing a new escape direction every simulation step.
        """
        runtime = self.runtime[name]
        if now < runtime.avoidance_cooldown_until:
            return False

        duration = max(0.1, float(self.collision_guard_cfg.get("avoidance_duration", 0.70)))
        cooldown = max(duration, float(self.collision_guard_cfg.get("avoidance_cooldown", 1.20)))
        runtime.avoidance_world_vx = float(world_vx)
        runtime.avoidance_world_vy = float(world_vy)
        runtime.avoidance_cooldown_until = now + cooldown

        if runtime.recovery_state == 0:
            runtime.avoidance_until = now + duration
            runtime.avoidance_pending = False
        else:
            runtime.avoidance_pending = True
        return True

    def apply_kick(self, name, msg):
        now = self.robot.getTime()
        runtime = self.runtime[name]
        kick_cfg = self.cfg["kick"]
        if runtime.recovery_state != 0 or now - runtime.last_kick < kick_cfg["cooldown"]:
            return
        ball_position = self.ball.getPosition()
        distance = math.hypot(ball_position[0] - runtime.x, ball_position[1] - runtime.y)
        if distance > kick_cfg["contact_distance"]:
            self.kick_packets_rejected_distance += 1
            print(
                f"[WEBOTS_GATEWAY][KICK][REJECT] robot={name} "
                f"distance={distance:.2f}m limit={kick_cfg['contact_distance']:.2f}m"
            )
            return
        rel_dir, ok_dir = self.finite_float(msg.get("dir", 0.0))
        power, ok_power = self.finite_float(msg.get("power", 2.5), 2.5)
        if not (ok_dir and ok_power):
            self.invalid_command_packets += 1
            return
        direction = runtime.yaw + rel_dir
        speed = clamp(power * 1.65, kick_cfg["min_speed"], kick_cfg["max_speed"])
        self.ball.setVelocity(
            [speed * math.cos(direction), speed * math.sin(direction), 0.20, 0.0, 0.0, 0.0]
        )
        runtime.last_kick = now
        self.kick_packets_applied += 1
        print(
            f"[WEBOTS_GATEWAY][KICK][APPLY] robot={name} "
            f"distance={distance:.2f}m speed={speed:.1f}m/s"
        )
        self.last_touch = name.split("_")[0]
        self.last_event = f"{name} kicked ({speed:.1f} m/s)"

    def update_phase(self):
        now = self.robot.getTime()
        elapsed = now - self.phase_started
        timing = self.cfg["timing"]
        if self.phase == "READY" and elapsed >= timing["ready"]:
            self.phase = "SET"
            self.phase_started = now
        elif self.phase == "SET" and elapsed >= timing["set"]:
            self.phase = "PLAYING"
            self.phase_started = now
        if self.phase == "PLAYING":
            self.match_time += max(0.0, now - self.last_time)
        if self.match_time >= timing["match_seconds"]:
            self.phase = "FINISHED"
        if self.set_play and now >= self.restart_release_at:
            self.stopped = 0
        self.last_time = now

    def update_recovery(self, name):
        runtime = self.runtime[name]
        now = self.robot.getTime()
        elapsed = now - runtime.recovery_started
        if runtime.recovery_state == 1 and elapsed >= 0.45:
            runtime.recovery_state = 2
            runtime.recovery_started = now
        elif runtime.recovery_state == 2:
            auto_get_up_after = float(self.collision_guard_cfg.get("auto_get_up_after", 0.0))
            if auto_get_up_after > 0.0 and elapsed >= auto_get_up_after:
                runtime.recovery_state = 3
                runtime.recovery_started = now
                self.last_event = f"{name} automatic get-up"
        elif runtime.recovery_state == 3 and elapsed >= 1.25:
            runtime.recovery_state = 0
            runtime.recovery_started = now
            if runtime.avoidance_pending:
                post_get_up = max(
                    0.1,
                    float(self.collision_guard_cfg.get("post_get_up_avoidance_duration", 0.85)),
                )
                runtime.avoidance_until = now + post_get_up
                runtime.avoidance_cooldown_until = max(
                    runtime.avoidance_cooldown_until, now + post_get_up
                )
                runtime.avoidance_pending = False

    def update_robot(self, name):
        runtime = self.runtime[name]
        self.update_recovery(name)
        command = self.commands[name]
        now = self.robot.getTime()
        motion_cfg = self.cfg["motion"]
        avoiding = (
            runtime.recovery_state == 0
            and now < runtime.avoidance_until
        )
        active = (
            self.phase == "PLAYING"
            and runtime.recovery_state == 0
            and now >= runtime.collision_lock_until
            and now - command.received_at <= self.cfg["command_timeout"]
        )
        if avoiding:
            target_vx, target_vy = world_to_local(
                runtime.avoidance_world_vx,
                runtime.avoidance_world_vy,
                runtime.yaw,
            )
            target_vyaw = 0.0
        elif name == "red_5" and now < self.debug_move_until and runtime.recovery_state == 0:
            target_vx, target_vy, target_vyaw = (0.60, 0.0, 0.0)
        else:
            target_vx, target_vy, target_vyaw = (
                (command.vx, command.vy, command.vyaw) if active else (0.0, 0.0, 0.0)
            )

        runtime.vx = self.approach(runtime.vx, target_vx, motion_cfg["linear_accel"] * self.dt)
        runtime.vy = self.approach(runtime.vy, target_vy, motion_cfg["linear_accel"] * self.dt)
        runtime.vyaw = self.approach(runtime.vyaw, target_vyaw, motion_cfg["yaw_accel"] * self.dt)
        if runtime.recovery_state != 0:
            runtime.vx = runtime.vy = runtime.vyaw = 0.0

        world_vx, world_vy = local_to_world(runtime.vx, runtime.vy, runtime.yaw)
        robot_limit_x, robot_limit_y = self.robot_motion_limits()
        runtime.x = clamp(runtime.x + world_vx * self.dt, -robot_limit_x, robot_limit_x)
        runtime.y = clamp(runtime.y + world_vy * self.dt, -robot_limit_y, robot_limit_y)
        runtime.yaw = wrap_angle(runtime.yaw + runtime.vyaw * self.dt)

        speed = math.hypot(runtime.vx, runtime.vy)
        runtime.walk_phase += self.dt * (2.5 + 6.0 * speed)
        z = 0.012 * abs(math.sin(runtime.walk_phase)) if speed > 0.05 else 0.0
        pitch = roll = 0.0
        if runtime.recovery_state == 1:
            amount = clamp((now - runtime.recovery_started) / 0.45, 0.0, 1.0)
            pitch = (1 if int(name[-1]) % 2 else -1) * 1.45 * amount
            z = -0.12 * amount
        elif runtime.recovery_state == 2:
            pitch = (1 if int(name[-1]) % 2 else -1) * 1.45
            z = -0.12
        elif runtime.recovery_state == 3:
            amount = clamp((now - runtime.recovery_started) / 1.25, 0.0, 1.0)
            pitch = (1 if int(name[-1]) % 2 else -1) * 1.45 * (1.0 - amount)
            z = -0.12 * (1.0 - amount)
        elif speed > 0.05:
            roll = 0.025 * math.sin(runtime.walk_phase)

        self.trans[name].setSFVec3f([runtime.x, runtime.y, z])
        self.rot[name].setSFRotation(yaw_tilt_rotation(runtime.yaw, pitch, roll))

    def resolve_robot_overlaps(self):
        """Approximate 2-D rigid-body contacts for locked kinematic proxies.

        The robots are still moved by root translation, so this is not full multibody
        dynamics. Compared with the old symmetric push-apart guard, this model applies
        positional correction, a normal collision impulse, tangential friction, a short
        control stun, and optional fall events for high-speed or side impacts.
        """
        if not bool(self.collision_guard_cfg.get("enabled", True)):
            return

        minimum = float(self.collision_guard_cfg.get("minimum_center_distance", 0.76))
        iterations = max(1, int(self.collision_guard_cfg.get("iterations", 4)))
        mass = max(1.0, float(self.collision_guard_cfg.get("mass_kg", 35.0)))
        inv_mass = 1.0 / mass
        restitution = clamp(float(self.collision_guard_cfg.get("restitution", 0.05)), 0.0, 1.0)
        friction = max(0.0, float(self.collision_guard_cfg.get("tangential_friction", 0.65)))
        correction_ratio = clamp(float(self.collision_guard_cfg.get("position_correction", 0.90)), 0.0, 1.0)
        stun = max(0.0, float(self.collision_guard_cfg.get("collision_stun", 0.18)))
        fall_enabled = bool(self.collision_guard_cfg.get("fall_enabled", True))
        fall_front = max(0.0, float(self.collision_guard_cfg.get("fall_relative_speed", 1.65)))
        fall_side = max(0.0, float(self.collision_guard_cfg.get("fall_side_speed", 1.25)))
        fall_both = max(fall_front, float(self.collision_guard_cfg.get("fall_both_speed", 1.95)))
        fall_cooldown = max(0.0, float(self.collision_guard_cfg.get("fall_cooldown", 3.0)))
        avoidance_enabled = bool(self.collision_guard_cfg.get("avoidance_enabled", True))
        avoidance_trigger = max(
            0.0, float(self.collision_guard_cfg.get("avoidance_trigger_speed", 0.10))
        )
        avoidance_side = max(
            0.0, float(self.collision_guard_cfg.get("avoidance_side_speed", 0.42))
        )
        avoidance_backoff = max(
            0.0, float(self.collision_guard_cfg.get("avoidance_backoff_speed", 0.28))
        )
        now = self.robot.getTime()
        resolved = 0
        impacts = 0
        falls = 0
        avoids = 0

        for _ in range(iterations):
            changed = False
            for i, first_name in enumerate(ROBOT_NAMES):
                first = self.runtime[first_name]
                for j in range(i + 1, len(ROBOT_NAMES)):
                    second_name = ROBOT_NAMES[j]
                    second = self.runtime[second_name]
                    dx = second.x - first.x
                    dy = second.y - first.y
                    distance = math.hypot(dx, dy)
                    if distance >= minimum:
                        continue

                    if distance < 1e-9:
                        angle = ((i * 17 + j * 31) % 360) * math.pi / 180.0
                        nx, ny = math.cos(angle), math.sin(angle)
                        distance = 0.0
                    else:
                        nx, ny = dx / distance, dy / distance

                    penetration = minimum - distance
                    correction = 0.5 * correction_ratio * max(0.0, penetration + 1e-4)
                    robot_limit_x, robot_limit_y = self.robot_motion_limits()
                    first.x = clamp(first.x - nx * correction, -robot_limit_x, robot_limit_x)
                    first.y = clamp(first.y - ny * correction, -robot_limit_y, robot_limit_y)
                    second.x = clamp(second.x + nx * correction, -robot_limit_x, robot_limit_x)
                    second.y = clamp(second.y + ny * correction, -robot_limit_y, robot_limit_y)

                    v1x, v1y = local_to_world(first.vx, first.vy, first.yaw)
                    v2x, v2y = local_to_world(second.vx, second.vy, second.yaw)
                    rvx, rvy = v2x - v1x, v2y - v1y
                    normal_speed = rvx * nx + rvy * ny
                    impact_speed = max(0.0, -normal_speed)

                    if normal_speed < 0.0:
                        normal_impulse = -(1.0 + restitution) * normal_speed / (2.0 * inv_mass)
                        ix, iy = normal_impulse * nx, normal_impulse * ny
                        v1x -= ix * inv_mass
                        v1y -= iy * inv_mass
                        v2x += ix * inv_mass
                        v2y += iy * inv_mass

                        tx, ty = -ny, nx
                        tangential_speed = rvx * tx + rvy * ty
                        tangent_impulse = -tangential_speed / (2.0 * inv_mass)
                        max_tangent = friction * normal_impulse
                        tangent_impulse = clamp(tangent_impulse, -max_tangent, max_tangent)
                        tix, tiy = tangent_impulse * tx, tangent_impulse * ty
                        v1x -= tix * inv_mass
                        v1y -= tiy * inv_mass
                        v2x += tix * inv_mass
                        v2y += tiy * inv_mass

                        first.vx, first.vy = world_to_local(v1x, v1y, first.yaw)
                        second.vx, second.vy = world_to_local(v2x, v2y, second.yaw)
                        first.collision_lock_until = max(first.collision_lock_until, now + stun)
                        second.collision_lock_until = max(second.collision_lock_until, now + stun)
                        impacts += 1

                        # Low/medium contacts are expected in football. Move the two
                        # robots along opposite tangential directions plus a small
                        # normal back-off. This temporarily overrides their Brain
                        # commands and guarantees that a symmetric head-on contact
                        # cannot repeat forever.
                        if avoidance_enabled and impact_speed >= avoidance_trigger:
                            tx, ty = -ny, nx
                            # Alternate the tangent deterministically between pairs;
                            # neither team receives a permanent left/right advantage.
                            side_sign = 1.0 if (i + j) % 2 == 0 else -1.0
                            first_escape_x = -nx * avoidance_backoff + tx * avoidance_side * side_sign
                            first_escape_y = -ny * avoidance_backoff + ty * avoidance_side * side_sign
                            second_escape_x = nx * avoidance_backoff - tx * avoidance_side * side_sign
                            second_escape_y = ny * avoidance_backoff - ty * avoidance_side * side_sign
                            if self.schedule_collision_avoidance(
                                first_name, first_escape_x, first_escape_y, now
                            ):
                                avoids += 1
                            if self.schedule_collision_avoidance(
                                second_name, second_escape_x, second_escape_y, now
                            ):
                                avoids += 1

                        if fall_enabled and first_name.split("_")[0] != second_name.split("_")[0]:
                            first_contact = abs(math.cos(first.yaw) * nx + math.sin(first.yaw) * ny)
                            second_contact = abs(math.cos(second.yaw) * (-nx) + math.sin(second.yaw) * (-ny))
                            side_contact = min(first_contact, second_contact) < 0.45
                            threshold = fall_side if side_contact else fall_front
                            eligible_first = (
                                first.recovery_state == 0
                                and now - first.last_collision_fall >= fall_cooldown
                            )
                            eligible_second = (
                                second.recovery_state == 0
                                and now - second.last_collision_fall >= fall_cooldown
                            )
                            if impact_speed >= fall_both:
                                for robot_name, runtime in ((first_name, first), (second_name, second)):
                                    if runtime.recovery_state == 0 and now - runtime.last_collision_fall >= fall_cooldown:
                                        runtime.last_collision_fall = now
                                        self.start_fall(robot_name)
                                        falls += 1
                            elif impact_speed >= threshold:
                                # The robot struck more from its side/back is less stable.
                                victim_name, victim = (
                                    (first_name, first)
                                    if first_contact <= second_contact
                                    else (second_name, second)
                                )
                                victim_eligible = eligible_first if victim is first else eligible_second
                                if victim_eligible:
                                    victim.last_collision_fall = now
                                    self.start_fall(victim_name)
                                    falls += 1

                    resolved += 1
                    changed = True
            if not changed:
                break

        if not resolved:
            return
        self.robot_overlap_resolutions += resolved
        self.robot_collision_impacts += impacts
        self.robot_collision_falls += falls
        self.robot_collision_avoids += avoids
        for name in ROBOT_NAMES:
            runtime = self.runtime[name]
            self.trans[name].setSFVec3f([runtime.x, runtime.y, self.trans[name].getSFVec3f()[2]])

        period = float(self.collision_guard_cfg.get("log_period", 2.0))
        if now - self.last_overlap_log_time >= period:
            self.last_overlap_log_time = now
            print(
                f"[WEBOTS_GATEWAY][COLLISION_MODEL] contacts={resolved} impacts={impacts} "
                f"falls={falls} avoids={avoids} "
                f"total_contacts={self.robot_overlap_resolutions} total_falls={self.robot_collision_falls} "
                f"min_center={minimum:.2f}m"
            )

    def restart(self, set_play, kicking_team, position, event):
        self.place_ball(position, reason=event)
        self.restart_id += 1
        self.restart_started_at = self.robot.getTime()
        self.restart_ball_position = [float(position[0]), float(position[1])]
        self.set_play = set_play
        self.kicking_team = kicking_team
        self.stopped = 1
        self.restart_release_at = self.robot.getTime() + self.cfg["timing"]["set_play_stop"]
        self.last_event = event
        print(
            f"[WEBOTS_GATEWAY][RESTART] id={self.restart_id} type={set_play} "
            f"team={kicking_team} event={event}"
        )

    def check_ball_rules(self):
        if self.phase != "PLAYING":
            return
        position = self.ball.getPosition()
        if not all(math.isfinite(value) for value in position[:3]):
            return
        x, y, _ = position
        half_length = self.cfg["field"]["length"] / 2.0
        half_width = self.cfg["field"]["width"] / 2.0
        goal_half_width = self.cfg["field"]["goal_width"] / 2.0
        red_id = self.cfg["team_ids"]["red"]
        blue_id = self.cfg["team_ids"]["blue"]

        if x > half_length and abs(y) <= goal_half_width:
            self.score["red"] += 1
            self.last_event = "GOAL RED"
            self.reset_after_goal(blue_id)
        elif x < -half_length and abs(y) <= goal_half_width:
            self.score["blue"] += 1
            self.last_event = "GOAL BLUE"
            self.reset_after_goal(red_id)
        elif abs(y) > half_width:
            owner = blue_id if self.last_touch == "red" else red_id
            self.restart(
                4,
                owner,
                (clamp(x, -half_length, half_length), math.copysign(half_width, y), self.ball_guard_cfg["nominal_z"]),
                "throw-in",
            )
        elif abs(x) > half_length:
            defending = "red" if x < 0 else "blue"
            defending_id = red_id if defending == "red" else blue_id
            attacking_id = blue_id if defending == "red" else red_id
            if self.last_touch == defending:
                self.restart(
                    6,
                    attacking_id,
                    (
                        math.copysign(half_length - 0.45, x),
                        math.copysign(half_width - 0.45, y if abs(y) > 1e-6 else 1.0),
                        self.ball_guard_cfg["nominal_z"],
                    ),
                    "corner kick",
                )
            else:
                self.restart(
                    5,
                    defending_id,
                    (0.0, math.copysign(half_width, y if abs(y) > 1e-6 else 1.0), self.ball_guard_cfg["nominal_z"]),
                    "goal kick",
                )

    def guard_ball(self):
        if not bool(self.ball_guard_cfg.get("enabled", True)):
            return
        position = list(self.ball.getPosition())
        velocity = list(self.ball.getVelocity())
        if len(position) < 3 or len(velocity) < 3:
            self.reset_ball_guard("invalid Webots ball vector")
            return
        if not all(math.isfinite(value) for value in position[:3]):
            self.reset_ball_guard(f"non-finite position {position[:3]}")
            return
        if not all(math.isfinite(value) for value in velocity):
            self.reset_ball_guard("non-finite velocity")
            return

        x, y, z = position[:3]
        if z < float(self.ball_guard_cfg["min_z"]):
            self.reset_ball_guard(f"below field z={z:.3f}")
            return
        if z > float(self.ball_guard_cfg["max_z"]):
            self.reset_ball_guard(f"too high z={z:.3f}")
            return
        if abs(x) > float(self.ball_guard_cfg["safety_x"]):
            self.reset_ball_guard(f"outside safety x={x:.3f}")
            return
        if abs(y) > float(self.ball_guard_cfg["safety_y"]):
            self.reset_ball_guard(f"outside safety y={y:.3f}")
            return

        linear_speed = math.sqrt(sum(component * component for component in velocity[:3]))
        max_speed = float(self.ball_guard_cfg["max_linear_speed"])
        if linear_speed > max_speed and linear_speed > 1e-9:
            scale = max_speed / linear_speed
            clamped_velocity = [component * scale for component in velocity[:3]] + velocity[3:6]
            self.ball.setVelocity(clamped_velocity)
            self.ball_velocity_clamps += 1
            print(
                f"[WEBOTS_GATEWAY][BALL][CLAMP] speed={linear_speed:.2f} -> {max_speed:.2f} m/s "
                f"count={self.ball_velocity_clamps}"
            )

        self.last_safe_ball_position = [x, y, z]

    def apply_ball_rolling_resistance(self):
        """Add grass-like rolling resistance without overriding airborne motion."""
        if not bool(self.ball_physics_cfg.get("enabled", True)):
            return
        position = self.ball.getPosition()
        velocity = list(self.ball.getVelocity())
        if len(position) < 3 or len(velocity) < 6:
            return
        nominal_z = float(self.ball_guard_cfg.get("nominal_z", 0.12))
        ground_tolerance = max(0.0, float(self.ball_physics_cfg.get("ground_z_tolerance", 0.055)))
        if position[2] > nominal_z + ground_tolerance:
            return

        vx, vy = velocity[0], velocity[1]
        speed = math.hypot(vx, vy)
        if speed <= 1e-9:
            return
        ground_deceleration = max(0.0, float(self.ball_physics_cfg.get("ground_deceleration", 0.78)))
        air_drag = max(0.0, float(self.ball_physics_cfg.get("air_drag", 0.10)))
        stop_speed = max(0.0, float(self.ball_physics_cfg.get("stop_speed", 0.09)))
        new_speed = max(0.0, speed - ground_deceleration * self.dt)
        new_speed *= math.exp(-air_drag * self.dt)
        if new_speed <= stop_speed:
            velocity[0] = 0.0
            velocity[1] = 0.0
            velocity[3] *= 0.4
            velocity[4] *= 0.4
            velocity[5] *= 0.4
        else:
            scale = new_speed / speed
            velocity[0] *= scale
            velocity[1] *= scale
        self.ball.setVelocity(velocity)
        self.ball_drag_steps += 1

    def reset_after_goal(self, kick_team):
        score = dict(self.score)
        match_time = self.match_time
        event = self.last_event
        self.reset_positions(False)
        self.score = score
        self.match_time = match_time
        self.kicking_team = kick_team
        self.last_event = event

    def keyboard_actions(self):
        while True:
            key = self.keyboard.getKey()
            if key == -1:
                break
            code = key & 0xFF
            char = chr(code).upper() if code < 256 else ""
            if char == "1":
                self.place_ball([self.cfg["field"]["length"] / 2.0 + 0.25, 0.0, self.ball_guard_cfg["nominal_z"]], reason="keyboard goal red")
            elif char == "2":
                self.place_ball([-self.cfg["field"]["length"] / 2.0 - 0.25, 0.0, self.ball_guard_cfg["nominal_z"]], reason="keyboard goal blue")
            elif char == "F":
                self.start_fall("red_2")
            elif char == "M":
                self.debug_move_until = self.robot.getTime() + 2.0
                self.last_event = "local execution test: red_5 moves for 2s"
                print("[WEBOTS_GATEWAY] local execution self-test started for red_5")
            elif char == "R":
                self.reset_positions(True)
            elif char == "K":
                self.reset_positions(False)

    def state_payload(self):
        ball_position = self.ball.getPosition()
        ball_velocity = self.ball.getVelocity()
        robots = {}
        for name, runtime in self.runtime.items():
            robots[name] = {
                "x": runtime.x,
                "y": runtime.y,
                "z": self.nodes[name].getPosition()[2],
                "theta": runtime.yaw,
                "recovery_state": runtime.recovery_state,
                "recovery_available": runtime.recovery_available,
            }
        state_map = {"INITIAL": 0, "READY": 1, "SET": 2, "PLAYING": 3, "FINISHED": 4}
        return {
            "version": 1,
            "type": "world_state",
            "sim_time": self.robot.getTime(),
            "match_time": self.match_time,
            "phase": self.phase,
            "gc_state": state_map.get(self.phase, 0),
            "set_play": self.set_play,
            "stopped": self.stopped,
            "kicking_team": self.kicking_team,
            "restart": {
                "id": self.restart_id,
                "active": bool(self.set_play),
                "set_play": self.set_play,
                "stopped": self.stopped,
                "kicking_team": self.kicking_team,
                "started_at": self.restart_started_at,
                "ball_x": self.restart_ball_position[0],
                "ball_y": self.restart_ball_position[1],
                "event": self.last_event,
            },
            "team_ids": self.cfg["team_ids"],
            "field": self.cfg["field"],
            "referee": {
                "mode": self.referee_cfg.get("mode", "internal_simulated"),
                "official_udp_enabled": bool(
                    self.referee_cfg.get("official_udp_game_controller_enabled", False)
                ),
            },
            "score": self.score,
            "last_event": self.last_event,
            "last_touch": self.last_touch,
            "ball_guard": {
                "resets": self.ball_resets,
                "velocity_clamps": self.ball_velocity_clamps,
                "drag_steps": self.ball_drag_steps,
            },
            "collision_guard": {
                "overlap_resolutions": self.robot_overlap_resolutions,
                "impacts": self.robot_collision_impacts,
                "falls": self.robot_collision_falls,
                "avoids": self.robot_collision_avoids,
                "minimum_center_distance": float(
                    self.collision_guard_cfg.get("minimum_center_distance", 0.72)
                ),
            },
            "ball": {
                "x": ball_position[0],
                "y": ball_position[1],
                "z": ball_position[2],
                "vx": ball_velocity[0],
                "vy": ball_velocity[1],
                "vz": ball_velocity[2],
            },
            "robots": robots,
        }

    def send_state(self):
        period = 1.0 / self.cfg["state_hz"]
        now = self.robot.getTime()
        if now - self.last_state_tx < period:
            return
        self.last_state_tx = now
        try:
            payload = json.dumps(self.state_payload(), separators=(",", ":")).encode()
            self.tx.sendto(payload, self.state_target)
            self.state_packets_sent += 1
        except OSError as error:
            if int(now) % 5 == 0:
                print(f"[WEBOTS_GATEWAY] state send failed: {error}")

    def link_status(self):
        now = self.robot.getTime()
        command_connected = self.move_packets_received > 0 and now - self.last_command_time < 2.0
        state_connected = self.bridge_status_packets_received > 0 and now - self.last_bridge_ack_time < 2.0
        return command_connected, state_connected

    def scoreboard(self):
        self.robot.setLabel(
            0,
            f"RED {self.score['red']} : {self.score['blue']} BLUE",
            0.41,
            0.015,
            0.07,
            0xFFFFFF,
            0,
            "Arial",
        )
        self.robot.setLabel(
            1,
            f"{int(self.match_time)//60:02d}:{int(self.match_time)%60:02d} {self.phase} | {self.last_event}",
            0.30,
            0.085,
            0.03,
            0xFFF2A8,
            0,
            "Arial",
        )
        self.robot.setLabel(
            2,
            "RED: brain_v3 | BLUE: wangyifei_v1 | OFFICIAL FIELD 22x14 + 2m BUFFER",
            0.31,
            0.12,
            0.024,
            0xE8F4FF,
            0,
            "Arial",
        )
        command_connected, state_connected = self.link_status()
        command_text = "CONNECTED" if command_connected else "WAITING"
        state_text = "CONNECTED" if state_connected else "NO ACK"
        self.robot.setLabel(
            3,
            f"ROS2 CMD: {command_text} | WORLD STATE: {state_text} | TX {self.state_packets_sent} ACK {self.bridge_state_packets_received}",
            0.20,
            0.15,
            0.023,
            0xFFFFFF,
            0,
            "Arial",
        )
        ball_position = self.ball.getPosition()
        self.robot.setLabel(
            4,
            f"BALL ({ball_position[0]:+.2f},{ball_position[1]:+.2f},{ball_position[2]:+.2f}) | resets {self.ball_resets} clamps {self.ball_velocity_clamps}",
            0.27,
            0.18,
            0.021,
            0xFFFFFF,
            0,
            "Arial",
        )
        self.robot.setLabel(
            5,
            "REFEREE: INTERNAL SIMULATED (official UDP referee box not connected)",
            0.25,
            0.21,
            0.020,
            0xFFD8A8,
            0,
            "Arial",
        )

    def command_state(self, name, now):
        command = self.commands[name]
        if command.packet_count == 0:
            return "NO_DATA"
        if now - command.received_at > self.cfg["command_timeout"]:
            return "STALE"
        magnitude = abs(command.vx) + abs(command.vy) + abs(command.vyaw)
        return "STOP" if magnitude < 1e-3 else "MOVE"

    def format_team_commands(self, team, now):
        parts = []
        for index in range(1, 6):
            name = f"{team}_{index}"
            command = self.commands[name]
            state = self.command_state(name, now)
            parts.append(
                f"{name}={state}[{command.vx:+.2f},{command.vy:+.2f},{command.vyaw:+.2f}]"
            )
        return " ".join(parts)

    def log_ball(self, now):
        period = float(self.ball_guard_cfg.get("log_period", 2.0))
        if now - self.last_ball_log_time < period:
            return
        self.last_ball_log_time = now
        position = self.ball.getPosition()
        velocity = self.ball.getVelocity()
        print(
            f"[WEBOTS_GATEWAY][BALL] pos=({position[0]:+.3f},{position[1]:+.3f},{position[2]:+.3f}) "
            f"vel=({velocity[0]:+.3f},{velocity[1]:+.3f},{velocity[2]:+.3f}) "
            f"resets={self.ball_resets} clamps={self.ball_velocity_clamps} drag={self.ball_drag_steps} "
            f"contacts={self.robot_overlap_resolutions} falls={self.robot_collision_falls}"
        )

    def diagnostics(self):
        now = self.robot.getTime()
        if now - self.last_diag_time < 2.0:
            return
        self.last_diag_time = now
        active = sum(
            1 for command in self.commands.values()
            if now - command.received_at <= self.cfg["command_timeout"]
        )
        nonzero = sum(
            1 for name in ROBOT_NAMES
            if self.command_state(name, now) == "MOVE"
        )
        command_connected, state_connected = self.link_status()
        print(
            f"[WEBOTS_GATEWAY][DIAG] state_tx={self.state_packets_sent} "
            f"state_ack_rx={self.bridge_status_packets_received} bridge_state_rx={self.bridge_state_packets_received} "
            f"command_rx={self.command_packets_received} move_rx={self.move_packets_received} "
            f"kick_rx={self.kick_packets_received} kick_ok={self.kick_packets_applied} "
            f"kick_far={self.kick_packets_rejected_distance} "
            f"active={active} nonzero={nonzero} invalid={self.invalid_command_packets} "
            f"cmd_link={'OK' if command_connected else 'WAIT'} state_link={'OK' if state_connected else 'NO_ACK'} "
            f"last_robot={self.last_command_robot}"
        )
        print(f"[WEBOTS_GATEWAY][MOVE][RED]  {self.format_team_commands('red', now)}")
        print(f"[WEBOTS_GATEWAY][MOVE][BLUE] {self.format_team_commands('blue', now)}")
        self.log_ball(now)

        if now >= 5.0 and self.command_packets_received == 0 and not self.no_command_warning_printed:
            self.no_command_warning_printed = True
            print(
                "[WEBOTS_GATEWAY][WARN] No ROS2 commands received on UDP 10082. "
                "Start the WSL launch script and check Windows/WSL IPs and firewall. "
                "Press M to test the Webots execution backend locally."
            )
        if (
            now >= 5.0
            and self.state_packets_sent >= 20
            and self.bridge_status_packets_received == 0
            and not self.no_state_ack_warning_printed
        ):
            self.no_state_ack_warning_printed = True
            print(
                f"[WEBOTS_GATEWAY][WARN] World states are being sent to {self.state_target}, "
                "but no Bridge ACK has returned. WEBOTS_ROS_HOST is likely wrong or UDP 10081 is blocked."
            )

    def run(self):
        while self.robot.step(self.step_ms) != -1:
            self.receive_commands()
            self.keyboard_actions()
            self.update_phase()
            for name in ROBOT_NAMES:
                self.update_robot(name)
            self.resolve_robot_overlaps()
            self.check_ball_rules()
            self.apply_ball_rolling_resistance()
            self.guard_ball()
            self.scoreboard()
            self.send_state()
            self.diagnostics()


if __name__ == "__main__":
    Gateway().run()
